
modLoader="javafml" 
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/pouffy/mw-core/issues"
craftTweakerScripts="https://github.com/pouffy/mw-core/tree/main/crafttweaker_scripts"
[[mods]]
modId="mw_core"
version="${file.jarVersion}" 
displayName="Create: Milkyway"
#updateJSONURL="https://change.me.example.invalid/updates.json" 
displayURL="https://discord.gg/qbSrvgwYUq" 
logoFile="milkyway_plaque.png"
credits="MilkFur, Ridanisaurus, SkyJay1, Baab, xRohBust, Mr_Error, ShellTune, SveinTheUser, Kermit, Fehn, Kirgirbir, ! Adrikikicp, all the staff on Milkyway and more!"
authors="Pouffy"
description='''
Core mod for Create: Milkyway
Once I figure out dependencies they will exist but for now don't use this on it's own.
This mod has all the bonus features for the modpack Create: Milkyway including custom recipes, items, blocks and fluids.
'''
[[dependencies.mw_core]] 
    modId="forge" 
    mandatory=true 
    versionRange="[40,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.mw_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mw_core]]
    modId="create"
    mandatory=true
    versionRange="[mc1.18.2_v0.5.0d,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mw_core]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[mc1.18.2_v1.2.0,)"
    ordering="NONE"
    side="BOTH"